services:
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: message_service_prod
      POSTGRES_HOST_AUTH_METHOD: trust
  api:
    build:
      context: .
      target: production
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      PORT: 8080
      DATABASE_URL: postgres://postgres@postgres/message_service_prod?schema=public
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - api
    ports:
      - 8080:8080
