services:
  backend:
    build: .
    ports:
      - 8080:8080
      - 9229:9229 #debugg
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.pnpm-store
    command: pnpm start:docker
    environment:
      PORT: 8080
